# Generated by Django 4.1.5 on 2023-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
