# Generated by Django 4.1.3 on 2023-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='picture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
