# Generated by Django 4.1.5 on 2023-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_rename_feedback_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
