# Generated by Django 4.1.1 on 2022-10-20 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_alter_extenduser_end_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='end_dates',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='start_dates',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
