# Generated by Django 4.1.5 on 2023-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_alter_extenduser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='barangay',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='birth_cert',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='cog',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='cor',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='good_moral',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='mangyan',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
