# Generated by Django 4.1.5 on 2023-01-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_extenduser_barangay_extenduser_birth_cert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='barangay',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='birth_cert',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='cog',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='cor',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='good_moral',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='mangyan',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
