# Generated by Django 4.1.3 on 2023-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_municipality_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='municipality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
