# Generated by Django 4.1.1 on 2022-10-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_alter_extenduser_end_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='end_dates',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='start_dates',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
