# Generated by Django 4.1.5 on 2023-01-24 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0004_alter_extenduser_barangay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='TD1',
            new_name='nationality',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD10',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD11',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD12',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD13',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD14',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD15',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD2',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD3',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD4',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD5',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD6',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD7',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD8',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='TD9',
        ),
    ]
