# Generated by Django 4.1.3 on 2023-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0004_extenduser_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='municipal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
