# Generated by Django 4.1.5 on 2023-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0005_rename_td1_extenduser_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='ip_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='ip_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
