# Generated by Django 4.1.5 on 2023-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0006_extenduser_ip_category_extenduser_ip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='date_applied',
            field=models.DateTimeField(null=True),
        ),
    ]
