# Generated by Django 4.1.1 on 2022-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0006_alter_extenduser_end_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='end_dates',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='start_dates',
            field=models.DateTimeField(null=True),
        ),
    ]
