# Generated by Django 4.1.5 on 2023-01-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0007_extenduser_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='date_exam',
            field=models.DateTimeField(null=True),
        ),
    ]
