# Generated by Django 4.1.1 on 2022-10-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0007_remove_extenduser_end_dates_extenduser_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='end_date',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='start_dates',
            field=models.CharField(default='', max_length=15),
        ),
    ]
