# Generated by Django 4.1.1 on 2022-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0008_alter_extenduser_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='monthly_income',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='sources_income',
            field=models.CharField(default='', max_length=100),
        ),
    ]
