# Generated by Django 4.1.5 on 2023-01-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0009_extenduser_exam_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='care_of',
            field=models.CharField(default='', max_length=100),
        ),
    ]
