# Generated by Django 4.1.5 on 2023-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0010_extenduser_care_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='start',
            field=models.CharField(default='', max_length=100),
        ),
    ]
