# Generated by Django 4.1.5 on 2023-01-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0011_extenduser_end_extenduser_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='care_of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('picture', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
