# Generated by Django 4.1.5 on 2023-01-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0012_care_of'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='care_of',
            new_name='name_care_of',
        ),
    ]
